[kijanikiosk_api]
api-staging ansible_host=10.144.203.6

[kijanikiosk_payments]
payments-staging ansible_host=10.144.203.69

[kijanikiosk_logs]
logs-staging ansible_host=10.144.203.110

[kijanikiosk:children]
kijanikiosk_api
kijanikiosk_payments
kijanikiosk_logs

[kijanikiosk:vars]
ansible_python_interpreter=/usr/bin/python3
